version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: Asia/Tokyo

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: Asia/Tokyo
